{{- $ca := genCA "webhook-ca" 365 }}
{{- if (not .Values.externalCA) }}
kind: Secret
apiVersion: v1
metadata:
  name: webhook-issuer-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc (trim $ca.Cert) }}
  tls.key: {{ b64enc (trim $ca.Key) }}
  {{- end }}
